# Generated by Django 2.0.4 on 2018-04-18 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseChars', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('landingTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Airplane')),
                ('landingAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_landingAirport', to='flights.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(to='flights.Passenger'),
        ),
        migrations.AddField(
            model_name='flight',
            name='startingAirport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_startingAirport', to='flights.Airport'),
        ),
    ]
