# Generated by Django 2.0.4 on 2018-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ticketsPurchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrOfTickets',
            field=models.IntegerField(default=0),
        ),
    ]
