# Generated by Django 2.0.4 on 2018-05-07 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180507_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='landingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='startingDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='startingTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
