# Generated by Django 2.0.4 on 2018-05-11 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20180510_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nrOfTickets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
